const BAD_REQUEST = 400;
const SERVER_ERROR = 500;
const NOT_FOUND = 404;
const UNAUTHORIZED_ERROR = 401;
const SIGN_UP_ERROR = 409;
const ACCESS_ERROR_CODE = 403;
module.exports = {
  BAD_REQUEST, SERVER_ERROR, NOT_FOUND, UNAUTHORIZED_ERROR, SIGN_UP_ERROR, ACCESS_ERROR_CODE,
};
